#!/bin/sh
# rc_usb_service [mount|umount|remount|kmount|init|reconfig|stop]

run_usb_postserv() {
[ -z "$1" ] && set -- "stop"
for I in /etc/init.d/rc.post/usb_service/U[0-9][0-9]*; do [ -f $I ] && $I $1; done
}

case $1 in
stop)
run_usb_postserv stop
;;
"")
;;
*)
run_usb_postserv start
;;
esac

exit 0
