#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/sbin/scripts

UTC=yes

mount -n -t proc proc /proc
mount -n -t sysfs sysfs /sys
mount -n -t ramfs ramfs /home
mount -n -t ramfs ramfs /tmp
mount -n -t ramfs ramfs /mnt
mount -n -t ramfs ramfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t usbfs none /proc/bus/usb/

#mount Sercomm directory
mount -n -t jffs2  "mtd:factory" /config/factory
mount -n -t jffs2  "mtd:scnvram" /config/nvram
mount -n -t jffs2  "mtd:xxx" /config/xxx
mount -n -t jffs2  "mtd:language_ENU" /config/language_ENU
mount -n -t jffs2  "mtd:language_CHS" /config/language_CHS
mount -n -t jffs2  "mtd:language_RUS" /config/language_RUS
mount -n -t jffs2  "mtd:language_DEU" /config/language_DEU
mount -n -t jffs2  "mtd:language_FRA" /config/language_FRA
mount -n -t jffs2  "mtd:language_NLD" /config/language_NLD
mount -n -t jffs2  "mtd:language_SVE" /config/language_SVE
mount -n -t jffs2  "mtd:language_ITA" /config/language_ITA
mount -n -t jffs2  "mtd:language_KOR" /config/language_KOR
mount -n -t jffs2  "mtd:language_ESP" /config/language_ESP

# build var directories
/bin/mkdir -m 0777 /tmp/var
/bin/mkdir -m 0777 /var/lock
/bin/mkdir -m 0777 /var/log
/bin/mkdir -m 0777 /var/run
/bin/mkdir -m 0777 /var/tmp
/bin/mkdir -m 0777 /var/w
/bin/mkdir -m 0777 /tmp/etc
/bin/mkdir -m 0755 /etc/dnrd
/bin/mkdir -m 0777 /mnt/shares
/bin/mkdir -m 0777 /var/run/bftpd
/bin/mkdir -m 0777 /tmp/nv
/bin/mkdir -m 0777 /tmp/w
/bin/mkdir -m 0777 /tmp/itunes
/bin/mkdir -m 0777 /var/run/dbus
/bin/mkdir -m 0777 /var/run/down
/bin/mkdir -m 0777 /var/run/lock

/bin/cp -a /usr/etc/* /etc
/bin/cp -a /usr/dev/* /dev/

# insert modules
mount -t jffs2 "mtd:data" /data
/sbin/insmod /lib/modules/bdmf.ko bdmf_chrdev_major=215 
/sbin/insmod /lib/modules/rdpa_gpl.ko
/sbin/insmod /lib/modules/rdpa.ko
/sbin/insmod /lib/modules/rdpa_mw.ko
/sbin/insmod /lib/modules/chipinfo.ko
/sbin/insmod /lib/modules/bcmxtmrtdrv.ko
/sbin/insmod /lib/modules/bcmxtmcfg.ko
/sbin/insmod /lib/modules/bcm_ingqos.ko
/sbin/insmod /lib/modules/bcm_bpm.ko
/sbin/insmod /lib/modules/pktflow.ko
/sbin/insmod /lib/modules/bcmfap.ko
/sbin/insmod /lib/modules/pktrunner.ko
/sbin/insmod /lib/modules/adsldd.ko
/sbin/insmod /lib/modules/bcm_enet.ko
/sbin/insmod /lib/modules/nciTMSkmod.ko
/sbin/insmod /lib/modules/bcmarl.ko
/sbin/insmod /lib/modules/bcmvlan.ko
/sbin/insmod /lib/modules/pwrmngtd.ko

/sbin/insmod /lib/modules/rdpa_cmd_tm.ko
/sbin/insmod /lib/modules/rdpa_cmd_spdsvc.ko
/sbin/insmod /lib/modules/rdpa_cmd_ds_wan_udp_filter.ko
/sbin/insmod /lib/modules/rdpa_cmd_drv.ko

/sbin/insmod /lib/modules/led_pb_api.ko
/sbin/insmod /lib/modules/led_hw.ko

#broadcomm has made some LED control, so make it off. After this control moved, should delete it too.
/bin/echo 0300 > /proc/led

# LED show we are booting...
/usr/sbin/led_app on 71

/sbin/insmod /lib/modules/ipt_REJECT.ko
/sbin/insmod /lib/modules/ipt_condition.ko
/sbin/insmod /lib/modules/ipt_http_string.ko
/sbin/insmod /lib/modules/ipt_dnshj.ko
/sbin/insmod /lib/modules/ipt_DLOG.ko
/sbin/insmod /lib/modules/xt_ct_dir.ko

/sbin/insmod /lib/modules/cnapt_core.ko
/sbin/insmod /lib/modules/cnapt.ko
/sbin/insmod /lib/modules/cpt.ko
/sbin/insmod /lib/modules/cpm.ko
/sbin/insmod /lib/modules/calg.ko
/sbin/insmod /lib/modules/cdmz.ko
/sbin/insmod /lib/modules/cudp.ko
/sbin/insmod /lib/modules/hairpin.ko
/sbin/insmod /lib/modules/natlimit.ko
#paragon ntfs 
/sbin/insmod /lib/modules/ufsd.ko

#ipv6
insmod /lib/modules/ip6_tables.ko
insmod /lib/modules/ip6table_filter.ko
insmod /lib/modules/ip6table_raw.ko
insmod /lib/modules/ip6table_mangle.ko
insmod /lib/modules/ip6t_LOG.ko
insmod /lib/modules/nf_defrag_ipv6.ko
insmod /lib/modules/nf_conntrack_ipv6.ko

#insert SPI firewall module
/etc/do.sh

#add for vpn
mknod /dev/spu c 233 0
/sbin/insmod /lib/modules/ipt_vpntrigger.ko
/usr/sbin/spuctl start

# wifi modules
insmod /lib/modules/wfd.ko
insmod /lib/modules/wlcsm.ko
insmod /lib/modules/wlemf.ko
insmod /lib/modules/wl.ko

# insert usb modules
/sbin/insmod /lib/modules/libata.ko
/sbin/insmod /lib/modules/libahci.ko
/sbin/insmod /lib/modules/ahci.ko
/sbin/insmod /lib/modules/bcm63xx_sata.ko
/sbin/insmod /lib/modules/ahci_platform.ko
/sbin/insmod /lib/modules/ehci-hcd.ko
/sbin/insmod /lib/modules/ohci-hcd.ko
/sbin/insmod /lib/modules/xhci-hcd.ko
/sbin/insmod /lib/modules/bcm63xx_usb.ko

/bin/echo "insmod finish" > /dev/console

# start brcm switch
/usr/sbin/swmdk &
/bin/sleep 2

# stamp lan start time
/bin/cp /proc/uptime /tmp/lan_uptime

ifconfig lo 127.0.0.1
route add -net 127.0.0.0 netmask 255.0.0.0 lo

#igmp v3 for netgear spec 1.9
echo "3" > /proc/sys/net/ipv4/conf/all/force_igmp_version

cp -f /usr/sbin/setupwizard.cgi /tmp/setupwizard.cgi
/sbin/klogd&

# Move up by Joel for DG834NR WPA function.
/usr/sbin/cmd_agent_ap

echo 2 > /proc/sys/net/ipv6/conf/all/forwarding
echo 1 > /proc/sys/net/ipv6/conf/all/autoconf
echo 1 > /proc/sys/net/ipv6/conf/default/autoconf

# set default, do not autoconf with RA pinfo (prefix info)
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo 0 > /proc/sys/net/ipv6/conf/all/accept_ra_pinfo
echo 0 > /proc/sys/net/ipv6/conf/default/accept_ra_pinfo

#mount
mount -a

/bin/sleep 1

if [ ! -e '/config/nvram/ready' ]
then
    /bin/echo "mount scnvram failed, calling eraseall " > /dev/console
    /bin/flash_eraseall -j /dev/mtd3
	/bin/mount -n -t jffs2  "mtd:scnvram" /config/nvram
	/bin/touch  /config/nvram/ready
fi
/bin/echo "=============mount finished " > /dev/console

# LAN switch setup
/bin/ethswctl -c pause -p 0 -v 1
/bin/ethswctl -c pause -p 1 -v 1
/bin/ethswctl -c pause -p 2 -v 1
/bin/ethswctl -c pause -p 3 -v 1

/usr/sbin/rc_app/rc_init 
/usr/sbin/scfgmgr&

/bin/echo "=============rc start " > /dev/console
/usr/sbin/rc start
/bin/echo "=============rc finish " > /dev/console

/usr/sbin/rc upnp start
/usr/sbin/crond &
/usr/sbin/multi_pb_app 90 91 92 10 40&
/usr/sbin/wlevt

# ancistrus
echo "=============ancistrus start " > /dev/console
echo "root:`anc nvram rget http_password`" | chpasswd
touch /etc/nologin
utelnetd -l /usr/sbin/login -d
# snr retrain: [ min -136 = 65400 ] ... [ -1 = 65535] 0 1 ... [ 100 = default ] ... [ 32767 max ]
# adslctl configure --snr [ 65400 - 65535 - 0 - 32767 ]
# 2.4Ghz tx pwr
# wl -i wl0 txpwr [ 1 - 160 ]
# 5Ghz tx pwr
# wl -i wl1 txpwr [ 1 - 160 ]
echo "=============ancistrus end " > /dev/console

#Ron add for upnpd
route add -net 239.0.0.0 netmask 255.0.0.0 br0

# router
echo 1 > /proc/sys/net/ipv4/ip_forward
# pppox
echo 1 > /proc/sys/net/ipv4/ip_dynaddr

# arp ignore
echo 1 > /proc/sys/net/ipv4/conf/all/arp_ignore

# add more conntrack
echo 4608 > /proc/sys/net/nf_conntrack_max

# ignore_all not yet used: this should be satisfactory
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

# set to 1 for lan static route, when wan is not up and ip_forward is 0.
echo 1 > /proc/sys/net/ipv4/conf/br0/forwarding
echo 1 > /proc/sys/net/ipv4/conf/wlan0/forwarding
echo 1 > /proc/sys/net/ipv4/conf/wlan0-va0/forwarding

# drop spoofed addr: turn this off when rip is on ?
# turn off for performance when fast_path is enabled
echo 1 > /proc/sys/net/ipv4/conf/eth1/rp_filter
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter

# do not honor source route flags
echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route

# Modify icmp time for netgear spec 1.9
echo 300 > /proc/sys/net/ipv4/netfilter/ip_conntrack_generic_timeout
echo 300 > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout_stream
echo 300 > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout
echo 60 > /proc/sys/net/ipv4/netfilter/ip_conntrack_icmp_timeout

# NTGR request change time from 30min to 2hour 4min at 08061107
echo 7440 > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_established
echo 60 > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_syn_sent

#remove session after get 2dirs FIN without timeout ? 
#BillGuo: we'd better not do this. FIN ACK packets may not be received yet. if we drop the session immediately,
#the FIN ACK packets will be treated as invalid NEW state, which (from lan) will go to wan without NAT or (from wan) be treated as ACK scan. 
echo 10 > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait

# USB
/sbin/insmod /lib/modules/usbserial_filter.ko
/sbin/insmod /lib/modules/GPL_NetUSB.ko
/sbin/insmod /lib/modules/NetUSB.ko

/bin/sleep 5

# Print server
/sbin/KC_BONJOUR &
/sbin/KC_PRINT &
/etc/turn_on_printer_led

