#!/bin/sh
#
# ancistrus
#
# Netgear's D7000 Nighthawk Router Experience Distributed Project
#
# https://github.com/negan07/ancistrus
#
# License: GPLv2
#
#
# 'rc_${SERV}' service inhibition script.
#
# Usage: $0 (<disable>)
#
# ${SERV} is a service run by 'rc_apps' through symlink 'rc_${SERV}' .
# Services that can be disabled are present as symlink named '${INITD}/${SERV}_pre' pointing to this script.
# Some services can be already disabled from web gui so no need to use this.
# Not all services can be disabled because essentials.
# This script can be skipped with 'nvram set anc_boot_disable=1' .
#
# Typing:
# 'rc $SERV disable'
# the service will be inhibited by 'anc' ('rc_apps') from running at all.
#

eval `nvram get anc_boot_disable` > /dev/null 2>&1
[ "${anc_boot_disable}" = "1" ] && exit 1		#skip flag

TAG=_pre
RCAPPDIR=/usr/sbin/rc_app
SERV=`basename $0`
SERV=${SERV%${TAG}}

case "$1" in
enable)							#enable service (remove inhibition)
nvram unset ${SERV}_disable
${RCAPPDIR}/rc_${SERV} start
;;
disable)						#disable service (add/enable inhibition)
${RCAPPDIR}/rc_${SERV} stop
nvram set ${SERV}_disable=1
;;
esac

eval `nvram get ${SERV}_disable` > /dev/null 2>&1
[ "`eval echo '$'${SERV}_disable`" = "1" ] && exit 127	#no exec cmd exit code

exit 0							#no inhibition
