#!/bin/sh
# Optional post wan connection commands

# Vars
TMPSCR=/tmp/wanpost
BIN=/usr/sbin/anc

# Debug purpose
#BIN=/etc/ancdbg/anc

# Copy optional post wan connection commands from nvram to a temporary file then run it
if [ -n "`${BIN} nvram rget anc_wan_opt`" ]; then
echo "#!/bin/sh" > ${TMPSCR}
${BIN} nvtotxt anc_wan_opt >> ${TMPSCR}
. ${TMPSCR} >/dev/null 2>&1
rm -f ${TMPSCR}
fi

exit 0
