include ../Rules.mak

all:
	@echo "Nothing to do: run 'make install' to install."

install:
#	install -m 0755 -d $(ETCDIR)/qos
#	install -m 0644 qos.conf $(ETCDIR)/qos
#	install -m 0644 qos.conf $(ETCDIR)
	install -m 0755 *.conf *.sh *.qos rc_qos $(BINDIR)/rc_app

clean: 
	@echo "Nothing to clean"

